### ISSUE TITLE
Which course the note for?

### ISSUE THREAD

**Issue by jzl2163** [lostcontrol2/Notes-of-Econometrics#1]
首先要感谢学长给我们带来了这么好的资料！
然后我想请问一下，这份资料是用于金融学院的计量经济学还是国际经济贸易学院的呢？
IFI416 or ECON301 ?
望解答，谢谢！

**Comment by dkl0707** [comment]
感谢关注。本笔记主要使用对象为选了ECON301（国际贸易学院）的学生。**但是这个笔记我还没写完（里面应该还有些错误会进行修正）。** 可能会在3月底更新。

Thanks for your attention to this project. This note is for ECON301, which is offered by School of International Trade and Economics, UIBE. **But I have not finished it yet (and there are some mistakes that need to be corrected).** It might be updated at the end of March, 2022.
